### ISSUE TITLE
识别出错，无法识别

### ISSUE THREAD

**Issue by annko11** [tomorinao-www/nonebot-plugin-anime-trace#1]
![image](https://github.com/tomorinao-www/nonebot-plugin-anime-trace/assets/139084066/132bd176-dd04-4fa5-9db6-c6fa463b9494)
错误情况如图，插件版本为最新，无报错

**Comment by tomorinao-www** [comment]
code:-1是网站的问题，可以去网站尝试能否识别https://ai.animedb.cn

**Comment by annko11** [comment]
确实是网站的问题，谢谢大佬
