### ISSUE TITLE
不知道算bug，还是QQ识别超链接的问题。

### ISSUE THREAD

**Issue by RainbowDashKira** [tomorinao-www/nonebot-plugin-anime-trace#5]
搜索结果提供的萌娘百科超链接会把，下一个选项开头的数字也算在里面，比如第一个检索结果是雷欧奥特曼，那么萌娘百科的超链接点开以后就会看到搜索关键词是雷欧奥特曼2.
![QQ20241023-151415](https://github.com/user-attachments/assets/27034ee2-d0c6-4ddb-a10d-0c1657c41253)

**Comment by tomorinao-www** [comment]
马上解决，谢谢反馈

**Comment by RainbowDashKira** [comment]
我不懂这个提供搜索的原理，如果可以的话，必应搜索可以换这个网站的检索https://www.animecharactersdatabase.com/cn/sort_characters.php?mt=2

**Comment by tomorinao-www** [comment]
好的，我不会玩这个网站，我看看

**Comment by RainbowDashKira** [comment]
www.animecharactersdatabase.com/cn/searchall.php?in=all&sq={q}   我自己尝试替换了一下 可以用。

**Comment by tomorinao-www** [comment]
我觉得不好用，用不惯这网站，我设置成可选的把

友利奈绪-勿忘我
***@***.***








---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月23日(周三) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomorinao-www/nonebot-plugin-anime-trace] 不知道算bug，还是QQ识别超链接的问题。 (Issue #5)




 
www.animecharactersdatabase.com/cn/searchall.php?in=all&amp;sq={q}   我自己尝试替换了一下 可以用。
 
&mdash;

**Comment by RainbowDashKira** [comment]
请问仓库clone的是最新的代码了么，我clone新代码以后，合并转发跟单独发送会一起发出来，之前是只有合并转发
![QQ20241024-090817](https://github.com/user-attachments/assets/31019471-dde4-4dfa-92ad-a02d015a38da)

**Comment by tomorinao-www** [comment]
不好意思喵，马上修复喵












友利奈绪-勿忘我
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月24日(周四) 上午9:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomorinao-www/nonebot-plugin-anime-trace] 不知道算bug，还是QQ识别超链接的问题。 (Issue #5)




 
请问仓库clone的是最新的代码了么，我clone新代码以后，合并转发跟单独发送会一起发出来，之前是只有合并转发
 QQ20241024-090817.png (view on web)
